apiVersion: apps/v1
kind: Deployment
metadata:
  name: yq-example
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      name: yq-example
  template:
    metadata:
      labels:
        name: yq-example
    spec:
      containers:
        - name: yq-example
          image: ' hello-world:linux'
          imagePullPolicy: Always
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: ENV
              value: production
      restartPolicy: Always
